spring.application.name=BertBuster
spring.datasource.url=jdbc:mysql://localhost:3306/bertbuster
spring.datasource.username=bertbuster
spring.datasource.password=${DB_PASSWORD:default_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
